export default [
  {
    name: "동",
    code: 1,
    holes: [
      {
        index: 1,
        code: 1,
        playTime: 15,
        par: 5,
        waitTime: 1,
      },
      {
        index: 2,
        code: 2,
        playTime: 12,
        par: 4,
        waitTime: 1,
      },
      {
        index: 3,
        code: 3,
        playTime: 13,
        par: 3,
        waitTime: 1,
      },
      {
        index: 4,
        code: 4,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 5,
        code: 5,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 6,
        code: 6,
        playTime: 10,
        par: 3,
        waitTime: 1,
      },
      {
        index: 7,
        code: 7,
        playTime: 18,
        par: 5,
        waitTime: 1,
      },
      {
        index: 8,
        code: 8,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 9,
        code: 9,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
    ],
    times: {
      total: "02:16",
      play: "02:08",
      waitEachHole: "00:08",
      waitEachCourse: "00:10",
    },
  },
  {
    name: "서",
    code: 2,
    holes: [
      {
        index: 1,
        code: 1,
        playTime: 15,
        par: 5,
        waitTime: 1,
      },
      {
        index: 2,
        code: 2,
        playTime: 12,
        par: 4,
        waitTime: 1,
      },
      {
        index: 3,
        code: 3,
        playTime: 13,
        par: 3,
        waitTime: 1,
      },
      {
        index: 4,
        code: 4,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 5,
        code: 5,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 6,
        code: 6,
        playTime: 10,
        par: 3,
        waitTime: 1,
      },
      {
        index: 7,
        code: 7,
        playTime: 18,
        par: 5,
        waitTime: 1,
      },
      {
        index: 8,
        code: 8,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 9,
        code: 9,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
    ],
    times: {
      total: "02:16",
      play: "02:08",
      waitEachHole: "00:08",
      waitEachCourse: "00:10",
    },
  },
  {
    name: "남",
    code: 3,
    holes: [
      {
        index: 1,
        code: 1,
        playTime: 15,
        par: 5,
        waitTime: 1,
      },
      {
        index: 2,
        code: 2,
        playTime: 12,
        par: 4,
        waitTime: 1,
      },
      {
        index: 3,
        code: 3,
        playTime: 13,
        par: 3,
        waitTime: 1,
      },
      {
        index: 4,
        code: 4,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 5,
        code: 5,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 6,
        code: 6,
        playTime: 10,
        par: 3,
        waitTime: 1,
      },
      {
        index: 7,
        code: 7,
        playTime: 18,
        par: 5,
        waitTime: 1,
      },
      {
        index: 8,
        code: 8,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 9,
        code: 9,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
    ],
    times: {
      total: "02:16",
      play: "02:08",
      waitEachHole: "00:08",
      waitEachCourse: "00:10",
    },
  },
  {
    name: "북",
    code: 4,
    holes: [
      {
        index: 1,
        code: 1,
        playTime: 15,
        par: 5,
        waitTime: 1,
      },
      {
        index: 2,
        code: 2,
        playTime: 12,
        par: 4,
        waitTime: 1,
      },
      {
        index: 3,
        code: 3,
        playTime: 13,
        par: 3,
        waitTime: 1,
      },
      {
        index: 4,
        code: 4,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 5,
        code: 5,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 6,
        code: 6,
        playTime: 10,
        par: 3,
        waitTime: 1,
      },
      {
        index: 7,
        code: 7,
        playTime: 18,
        par: 5,
        waitTime: 1,
      },
      {
        index: 8,
        code: 8,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
      {
        index: 9,
        code: 9,
        playTime: 15,
        par: 4,
        waitTime: 1,
      },
    ],
    times: {
      total: "02:16",
      play: "02:08",
      waitEachHole: "00:08",
      waitEachCourse: "00:10",
    },
  },
];
